###服务启动端口号
server:
  port: 80
  servlet:
    session:
      timeout: 7200
  max-http-header-size: 10000000
  tomcat: 
    basedir: temp
spring:
  servlet:
    multipart: 
      max-file-size: 10MB 
      max-request-size: 100MB
  application:
    name: miniblog

#图片上传路径
upload:
  path: data